services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: x99db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: x99db_test
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - '3333:3333'
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/x99db?schema=public
      JWT_ACCESS_SECRET: "greninjaemelhorquecharizardmilvezes"
      JWT_REFRESH_SECRET: "meuarceusporfavormeperdoe"
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - '8080:80'
    depends_on: 
      - backend

volumes:
  postgres_data:
  postgres_test_data: